apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: database-persistent-volume-claim
spec: 
  # Dynamic Provisioning of Persistent Volumes
  # storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi